version: '3'

volumes:
  local_db_data: {}


networks:
  knowquest_network:
    name: knowquest
    driver: bridge
    ipam:
      driver: default

services:
  app:
    container_name: django
    build:
      context: .
      dockerfile: Django-Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./.envs/.django
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      knowquest_network:
        aliases:
          - app
  
  db:
    container_name: postgres
    image: postgres:12.3
    environment:
      - POSTGRES_DB=hackaton
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin12345
    volumes:
      - local_db_data:/var/lib/postgresql/data
    networks:
      knowquest_network:
        aliases:
          - db