# Generated by Django 3.1.7 on 2022-09-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_study_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicDomains',
        ),
    ]
