# Generated by Django 3.1.7 on 2022-09-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_academicdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schools', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Study Area'),
        ),
    ]
