# Generated by Django 3.1.7 on 2022-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='delivery_mode',
            field=models.CharField(choices=[('O', 'Online'), ('P', 'Person')], default='P', max_length=10, verbose_name='Delivery Mode'),
        ),
        migrations.AddField(
            model_name='courses',
            name='picture',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='courses/picture/%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
