# Generated by Django 3.1.7 on 2022-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime'),
        ),
    ]
